server:
  port: 8085
spring:
  application:
    name: authentication-service
    security:
      jwt:
        secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
        access-token-expiration: 86400000
        refresh-token-expiration: 604800000

  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000      # 10 minutes
      max-lifetime: 1800000     # 30 minutes
      connection-timeout: 30000 # 30 seconds

  jpa:
      hibernate:
        ddl-auto: update           # or validate / create-drop / none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: false               # set to true for debugging SQL statements

logging:
  level:
    org.hibernate.SQL: WARN    # SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # bind parameter values
    org.springframework.security: DEBUG


