server:
  port: 8085
spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000      # 10 minutes
      max-lifetime: 1800000     # 30 minutes
      connection-timeout: 30000 # 30 seconds

  jpa:
      hibernate:
        ddl-auto: update           # or validate / create-drop / none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: false               # set to true for debugging SQL statements

logging:
  level:
    org.hibernate.SQL: WARN    # SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # bind parameter values

jwt:
  secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration-time: 36000000
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 15m
