spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/user_microservice
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000    # 15 minutes in milliseconds
    refresh-token-expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        orm:
          jpa: DEBUG
